#!/bin/bash

# display usage
function usage {
    echo "Usage: $0 <command> [<config_name>]";
    echo "";
    echo "Available commands:";
    echo "- init: Create the wordpress 'default' configuration.";
    echo "";
    echo "- create: Create a new wordpress configuration in <config_name>.";
    echo "          If a 'default' configuration exists, the newly created configuration ";
    echo "          is copied from it. Else, it is created from current WP installation.";
    echo "";
    echo "- activate: Activate an existing wordpress configuration.";
    echo "";
    echo "- list: List the available wordpress configurations.";
    echo "";
    echo "- current: Display currently active wordpress configuration.";
    echo "";
    echo "HOW TO:";
    echo "  1. Start with '$0 init'. This will create and activate a 'default' configuration equal to your current working WordPress.";
    echo "";
    echo "  2. Use '$0 create <config_name>' to create a new configuration copied from 'default'. Then edit './wp-configs/<config_name>/wp-config.php' if necessary. You also need to create a new database to match your new settings.";
    echo "          CREATE database <config_name> CHARACTER SET utf8mb4";
    echo "	    GRANT ALL PRIVILEGES on <config_name>.* to <user>";
    echo "";
    echo "  3. Use '$0 activate <config_name>' to load a configuration";
    
    exit 1;
}

# choose function to run according to command
function run {
    if [ $cmd == 'init' ]; then
	init
    elif [ $cmd == 'create' ]; then
	create
    elif [ $cmd == 'activate' ]; then
	activate
    elif [ $cmd == 'list' ]; then
	list
    elif [ $cmd == 'current' ]; then
	current
    else
	usage
    fi;
    
    exit 0;
}

# function to create symbolic link for a valid configuration.
# called by init and activate 
function _create_sym_links {
    ln -s wp-configs/$config/wp-config.php .;
    cd wp-content;
    ln -s ../wp-configs/$config/themes themes;
    ln -s ../wp-configs/$config/plugins plugins;
    cd ..;
}

# first command to execute to init a newly installed WordPress
# It creates the wp-configs folder and init a 'default' configuration
function init {
    if [ -d wp-configs/default ]; then
	echo "$cmd error: wp-configs/default already exists";
	exit 1;
    fi;

    if [[ -L wp-config.php ]]; then
	echo "$cmd error: wp-config.php is a symbolic link (directory already initialized?)";
	exit 2;
    fi;

    if [[ -L wp-content/themes ]]; then
	echo "$cmd error: wp-content/themes is a symbolic link (directory already initialized?)";
	exit 2;
    fi;

    if [[ -L wp-content/plugins ]]; then
	echo "$cmd error: wp-content/plugins is a symbolic link (directory already initialized?)";
	exit 2;
    fi;

    mkdir wp-configs wp-configs/$config;
    cp wp-config-sample.php wp-configs;
    mv wp-config.php wp-content/themes wp-content/plugins wp-configs/$config;
    _create_sym_links
}

# activate an existing configuration
function activate {
    if [ ! -d wp-configs/$config ]; then
	echo "$cmd error: wp-configs/$config does not exist";
	exit 1;
    fi;
    
    if [ ! -f wp-configs/$config/wp-config.php ]; then
	echo "$cmd error: wp-configs/$config/wp-config.php is missing";
	exit 1;
    fi;
    
    if [ ! -d wp-configs/$config/themes ]; then
	echo "$cmd error: wp-configs/$config/themes is missing";
	exit 1;
    fi;
    
    if [ ! -d wp-configs/$config/plugins ]; then
	echo "$cmd error: wp-configs/$config/plugins is missing";
	exit 1;
    fi;

    if [[ ! -L wp-config.php ]]; then
	echo "$cmd error: wp-config.php is not a symbolic link (did you run wp-config init?)";
	exit 2;
    fi;

    if [[ ! -L wp-content/themes ]]; then
	echo "$cmd error: wp-content/themes is not a symbolic link (did you run wp-config init?)";
	exit 2;
    fi;

    if [[ ! -L wp-content/plugins ]]; then
	echo "$cmd error: wp-content/plugins is not a symbolic link (did you run wp-config init?)";
	exit 2;
    fi;

    rm wp-config.php wp-content/themes wp-content/plugins;
    _create_sym_links
}

# activates an new configuration existing configuration
# replace the name of the DB in wp-config.php
function create {
    if [ -d wp-configs/$config ]; then
	echo "$cmd error: wp-configs/$config already exists";
	exit 1;
    fi;
    if [ ! -d wp-configs/default ]; then
	echo "$cmd error: wp-configs/default does not exist (did you run wp-config init?)";
	exit 1;
    fi
    cp -r wp-configs/default wp-configs/$config;
    sed -i -r s/\'DB_NAME\'\,\ \'[[:alnum:]]+\'/\'DB_NAME\'\,\ \'$config\'/ wp-configs/$config/wp-config.php;
    echo "$cmd warning: do not forget to create a new database '$config' before activating"
}

# lists the available configs
function list {
    ls -d wp-configs/*/ | sed s#/#''#g | sed s#wp-configs##
}

# displays current activated config
function current {
    ls -la wp-config.php | cut -f 2 -d '/'
}

# If not parameters are given, display usage
if [ $# -lt 1 ]; then
    usage
fi;

# set variables
# if command is 'init', always set config to 'default'
cmd=$1;
if [ $cmd == 'init' ]; then
    config='default'
else
    config=$2;
fi;

run;
